/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodosImport } from './routes/todos'
import { Route as InfiniteScrollImport } from './routes/infinite-scroll'
import { Route as DynamicFormImport } from './routes/dynamic-form'
import { Route as DebouncedSearchImport } from './routes/debounced-search'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TodosRoute = TodosImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRoute,
} as any)

const InfiniteScrollRoute = InfiniteScrollImport.update({
  id: '/infinite-scroll',
  path: '/infinite-scroll',
  getParentRoute: () => rootRoute,
} as any)

const DynamicFormRoute = DynamicFormImport.update({
  id: '/dynamic-form',
  path: '/dynamic-form',
  getParentRoute: () => rootRoute,
} as any)

const DebouncedSearchRoute = DebouncedSearchImport.update({
  id: '/debounced-search',
  path: '/debounced-search',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/debounced-search': {
      id: '/debounced-search'
      path: '/debounced-search'
      fullPath: '/debounced-search'
      preLoaderRoute: typeof DebouncedSearchImport
      parentRoute: typeof rootRoute
    }
    '/dynamic-form': {
      id: '/dynamic-form'
      path: '/dynamic-form'
      fullPath: '/dynamic-form'
      preLoaderRoute: typeof DynamicFormImport
      parentRoute: typeof rootRoute
    }
    '/infinite-scroll': {
      id: '/infinite-scroll'
      path: '/infinite-scroll'
      fullPath: '/infinite-scroll'
      preLoaderRoute: typeof InfiniteScrollImport
      parentRoute: typeof rootRoute
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/todos': typeof TodosRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/todos': typeof TodosRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/debounced-search': typeof DebouncedSearchRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/todos': typeof TodosRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/debounced-search'
    | '/dynamic-form'
    | '/infinite-scroll'
    | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/debounced-search'
    | '/dynamic-form'
    | '/infinite-scroll'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/debounced-search'
    | '/dynamic-form'
    | '/infinite-scroll'
    | '/todos'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DebouncedSearchRoute: typeof DebouncedSearchRoute
  DynamicFormRoute: typeof DynamicFormRoute
  InfiniteScrollRoute: typeof InfiniteScrollRoute
  TodosRoute: typeof TodosRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DebouncedSearchRoute: DebouncedSearchRoute,
  DynamicFormRoute: DynamicFormRoute,
  InfiniteScrollRoute: InfiniteScrollRoute,
  TodosRoute: TodosRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/debounced-search",
        "/dynamic-form",
        "/infinite-scroll",
        "/todos"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/debounced-search": {
      "filePath": "debounced-search.tsx"
    },
    "/dynamic-form": {
      "filePath": "dynamic-form.tsx"
    },
    "/infinite-scroll": {
      "filePath": "infinite-scroll.tsx"
    },
    "/todos": {
      "filePath": "todos.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
